name: Build and Upload Release APK to Github

# This will only trigger on pushes to main and Develop branches.
on:
  push:
    branches:
      - main
      - Develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Java (JDK 11)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Step 3: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.1'
    
    # Step 4: Create local.properties file
    - name: Create local.properties file
      run: |
        echo "sdk.dir=/usr/local/lib/android/sdk" > android/local.properties
        echo "flutter.sdk=/opt/hostedtoolcache/flutter/3.24.1-stable/x64" >> android/local.properties
        echo "flutter.buildMode=debug" >> android/local.properties
        echo "flutter.versionName=1.0.0" >> android/local.properties
        echo "flutter.versionCode=1" >> android/local.properties
        echo "flutter.minSdkVersion=23" >> android/local.properties
        echo "flutter.targetSdkVersion=34" >> android/local.properties
        echo "flutter.compileSdkVersion=34" >> android/local.properties

    # Step 5: Build the release APK
    - name: Build release APK
      run: flutter build apk --release

    # Step 6: Upload the build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Step 7: Checkout the repository again to get the artifact build that was created
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 8: Download the build artifacts from the previous job
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/

    # Step 9: Create a new release
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: Version_${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    # Step 10: Upload the APK to the release on GitHub
    - name: Upload APK
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive